# Effort Controllers ---------------------------------------
  # Publish all joint states -----------------------------------
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50 
    
arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
     - shoulder_pan_joint
     - shoulder_lift_joint
     - elbow_joint
     - wrist_1_joint
     - wrist_2_joint
     - wrist_3_joint
  constraints:
      goal_time: 0.04
      stopped_velocity_tolerance: 0.05
      shoulder_pan_joint: {trajectory: 0.005, goal: 0.005}
      shoulder_lift_joint: {trajectory: 0.005, goal: 0.005}
      elbow_joint: {trajectory: 0.005, goal: 0.005}
      wrist_1_joint: {trajectory: 0.005, goal: 0.005}
      wrist_2_joint: {trajectory: 0.005, goal: 0.005}
      wrist_3_joint: {trajectory: 0.005, goal: 0.005}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  gains: # Required because we're controlling an effort interface
    shoulder_pan_joint: {p: 1000,  d: 100, i: 0, i_clamp: 0}
    shoulder_lift_joint: {p: 1000,  d: 100, i: 0, i_clamp: 0}
    elbow_joint: {p: 1000,  d: 100, i: 0, i_clamp: 0}
    wrist_1_joint: {p: 1000,  d: 100, i: 0, i_clamp: 0}
    wrist_2_joint: {p: 1000,  d: 100, i: 0, i_clamp: 0}
    wrist_3_joint: {p: 1000,  d: 100, i: 0, i_clamp: 0}       
