ur_hardware_interface:
   joints: &robot_joints
     - shoulder_pan_joint
     - shoulder_lift_joint
     - elbow_joint
     - wrist_1_joint
     - wrist_2_joint
     - wrist_3_joint
hardware_control_loop:
   loop_hz: &loop_hz 500
   
arm_controller:
    # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  joints:
     - shoulder_pan_joint
     - shoulder_lift_joint
     - elbow_joint
     - wrist_1_joint
     - wrist_2_joint
     - wrist_3_joint
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_pan_joint
    pid: {p: 5.0, i: 0.05, d: 0.1}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_lift_joint
    pid: {p: 5.0, i: 0.05, d: 0.1}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: elbow_joint
    pid: {p: 5.0, i: 0.05, d: 0.1}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_1_joint
    pid: {p: 5.0, i: 0.05, d: 0.1}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_2_joint
    pid: {p: 5.0, i: 0.05, d: 0.1}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_3_joint
    pid: {p: 5.0, i: 0.05, d: 0.1}