# ## joint_state_controller
# $(arg prefix)joint_state_controller:
#     type: joint_state_controller/JointStateController
#     publish_rate: 50

# ## joint_group_position_controller
# $(arg prefix)hand_group_position_controller:
#     type: position_controllers/JointGroupPositionController
#     joints:
#       - $(arg prefix)finger_1_joint_1
#       - $(arg prefix)finger_2_joint_1
#       - $(arg prefix)finger_middle_joint_1
#       - $(arg prefix)palm_finger_1_joint

# ## single command controller JointTrajectoryController
# $(arg prefix)hand_simple_controller:
#     type: position_controllers/JointPositionController
#     joint: $(arg prefix)finger_1_joint_1
gripper:
  type: position_controllers/JointTrajectoryController
  joints:
    - gripper_palm_finger_1_joint
    - gripper_finger_1_joint_1
    - gripper_finger_1_joint_2
    - gripper_finger_1_joint_3
    - gripper_palm_finger_2_joint
    - gripper_finger_2_joint_1
    - gripper_finger_2_joint_2
    - gripper_finger_2_joint_3
    - gripper_finger_middle_joint_1
    - gripper_finger_middle_joint_2
    - gripper_finger_middle_joint_3
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      gripper_finger_1_joint_1: {trajectory: 0.5, goal: 0.5}
      gripper_finger_1_joint_2: {trajectory: 0.5, goal: 0.5}
      gripper_finger_1_joint_3: {trajectory: 0.5, goal: 0.5}
      gripper_finger_2_joint_1: {trajectory: 0.5, goal: 0.5}
      gripper_finger_2_joint_2: {trajectory: 0.5, goal: 0.5}
      gripper_finger_2_joint_3: {trajectory: 0.5, goal: 0.5}
      gripper_finger_middle_joint_1: {trajectory: 0.5, goal: 0.5}
      gripper_finger_middle_joint_2: {trajectory: 0.5, goal: 0.5}
      gripper_finger_middle_joint_3: {trajectory: 0.5, goal: 0.5}
      gripper_palm_finger_1_joint: {trajectory: 0.5, goal: 0.5}
      gripper_palm_finger_2_joint: {trajectory: 0.5, goal: 0.5}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  ##gains: 
  ##    gripper_finger_1_joint_1: {p: 10,  d: 0.1, i: 1, i_clamp: 1}
  ##    gripper_finger_1_joint_2: {p: 10,  d: 0.1, i: 1, i_clamp: 1}
  ##    gripper_finger_1_joint_3: {p: 10,  d: 0.1, i: 1, i_clamp: 1}
  ##    gripper_finger_2_joint_1: {p: 10,  d: 0.1, i: 1, i_clamp: 1}
  ##    gripper_finger_2_joint_2: {p: 10,  d: 0.1, i: 1, i_clamp: 1}
  ##    gripper_finger_2_joint_3: {p: 10,  d: 0.1, i: 1, i_clamp: 1}
  ##    gripper_finger_middle_joint_1: {p: 10,  d: 0.1, i: 1, i_clamp: 1}
  ##    gripper_finger_middle_joint_2: {p: 10,  d: 0.1, i: 1, i_clamp: 1}
  ##    gripper_finger_middle_joint_3: {p: 10,  d: 0.1, i: 1, i_clamp: 1}
  ##    gripper_palm_finger_1_joint: {p: 10,  d: 0.1, i: 1, i_clamp: 1}
  ##    gripper_palm_finger_2_joint: {p: 10,  d: 0.1, i: 1, i_clamp: 1}
joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - gripper_palm_finger_1_joint
    - gripper_finger_1_joint_1
    - gripper_finger_1_joint_2
    - gripper_finger_1_joint_3
    - gripper_palm_finger_2_joint
    - gripper_finger_2_joint_1
    - gripper_finger_2_joint_2
    - gripper_finger_2_joint_3
    - gripper_finger_middle_joint_1
    - gripper_finger_middle_joint_2
    - gripper_finger_middle_joint_3

