# ## joint_state_controller
# $(arg prefix)joint_state_controller:
#     type: joint_state_controller/JointStateController
#     publish_rate: 50

# ## joint_group_position_controller
# $(arg prefix)hand_group_position_controller:
#     type: position_controllers/JointGroupPositionController
#     joints:
#       - $(arg prefix)finger_1_joint_1
#       - $(arg prefix)finger_2_joint_1
#       - $(arg prefix)finger_middle_joint_1
#       - $(arg prefix)palm_finger_1_joint

# ## single command controller
# $(arg prefix)hand_simple_controller:
#     type: position_controllers/JointPositionController
#     joint: $(arg prefix)finger_1_joint_1

gripper:
  type: position_controllers/JointTrajectoryController
  joints:
     - gripper_finger1_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      finger1_joint: {trajectory: 0.1, goal: 0.1}

  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10